# AWS CodeBuild buildspec for testing and building the Speaker Role Classifier
# This file is embedded in the CDK pipeline stack but kept here for reference

version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.11
    commands:
      - echo Installing dependencies...
      - pip install --upgrade pip
      - pip install -e .[dev]

  pre_build:
    commands:
      - echo Running tests...
      - pytest tests/ -v --cov=speaker_role_classifier --cov-report=term

  build:
    commands:
      - echo Build started on `date`
      - echo Building Lambda deployment package...
      - echo Build completed successfully

artifacts:
  files:
    - '**/*'

cache:
  paths:
    - '/root/.cache/pip/**/*'
